### ISSUE TITLE
Пример работы

### ISSUE THREAD

**Issue by Tasnima1201** [zamgi/SentimentAnalysisService#1]
Добрый день!

Меня заинтересовал ваш проект, так как сама сейчас интересуюсь анализом тональностей текстов. Подскажите, пожалуйста, есть ли какой-нибудь пример работы или проект еще в разработке?

**Comment by zamgi** [comment]
проект уже рабочий. не могу найти бесплатный хостинг с поддержкой windows-сервисов (т.к. ядро выполнено в виде windows-сервиса). можете подсказать.
