### ISSUE TITLE
API url

### ISSUE THREAD

**Issue by avet-m** [zamgi/SentimentAnalysisService#2]
hi!  Is there a way to access to the API using some url ? 

Thx

**Comment by zamgi** [comment]
Hello! No way to access the API using a certain URL. (The URL indicated in the description is just for the demo). This service is not designed as a full-fledged REST web application. I can do it if it's necessary.

**Comment by avet-m** [comment]
Thank you for response. I want to use your solution in my paper work. So if you have possibility to provide an API for requests I will appreciate you. Thank you before hand.

**Comment by zamgi** [comment]
You welcome,  but I don't know when I will have time to do it.
