### ISSUE TITLE
Project binaries

### ISSUE THREAD

**Issue by hgfdd** [zamgi/SentimentAnalysisService#3]
Hello! 

Can you add/send some project binary files (.exe), at least its utility version. I'm mostly a linux developer and to start a windows virtual machine is not a problem, but install VS and build it and so on can be a problem. Maybe its another way to build the project? (some magic script:)

Thank you for responce

**Comment by zamgi** [comment]
Hello,

give me your email-address: i send binary files for you (if you can understand how use it).
